version: '2'
services:
    nginx-proxy:
        container_name: nginx-proxy
        image: nginxproxy/nginx-proxy
        ports:
            - "80:80"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
        depends_on:
            - miniprogram
            - website
    miniprogram:
        container_name: miniprogram
        image: golang
        volumes:
            - $PWD/miniprogram:/src
        command:
            - /src/miniprogram
        environment:
            - VIRTUAL_HOST=xlxj.local.cn
            - VIRTUAL_PORT=8080
    website:
        container_name: website
        image: nginx
        volumes:
            - $PWD/website:/usr/share/nginx/html
        environment:
            - VIRTUAL_HOST=xlxj_static.local.cn
            - VIRTUAL_PORT=80